### ISSUE TITLE
Misc Tasks to Finalize the Package

### ISSUE THREAD

**Issue by bryanhanson** [r-hyperspec/hySpc.read.jdx#11]
Some small things that still need to be done to complete the infrastructure. Assigned to Sang unless marked for Bryan.
- [x] Go through `CONTRIBUTING.md` and change references to `SKELETON` or `skeleton` to `hySpc.read.jdx` as appropriate.
- [x]  Rename `inst/fileio/read_jdx-EX.Rmd` to `hySpc-read-jdx.Rmd` and move it to the vignettes folder (which needs to be created at the top level).
- [x] Remove the files in `inst/fileio/jcamp-dx` If these are needed, use `system.file` to get them from `readJDX` directly.  Fix any functions examples or unit tests that rely on these files to use `system.file`.
- [x] After the above 2 steps the `inst` folder should be empty and can be deleted (I don't think it is required).
- [x] Delete `R/demo_function.R`.
- [x]  Delete `R/unittestdata.R`
- [x] `read_jdx` needs a unit test (I thought I saw this somewhere, maybe a draft pull).  UPDATE: yes, it's out there.
- [x] `read_jdx` needs an example. I suggest the same process as in the unit test.  Perhaps it should be wrapped in `\donttest{` but I'm not certain about that.
- [x] The vignette needs "front material" that sets up a lot of things.  See `hyperSpec.Rmd` for the needed material. There are also some additional files that need to be copied to this repo (should be clear from `hyperSpec.Rmd`).  After moving the needed material and files, do a basic edit to remove stuff that is clearly not appropriate for this repo.
- [x] Deprecate functions over in `hyperSpec` as needed.
- [x] Review the to-do list hidden in `README.md` and check off, complete or ideally delete the whole section because it's all done!
- [x] Bryan: review documentation in `read_jdx` Now tracked by issue #14 
- [x] Bryan: review vignette for consistency with the other vignettes (after Sang complete the front material). Now tracked by issue #13

**Comment by cbeleites** [comment]
- [x] delete vignette (see issue #13 )
- [ ] test on installation with CRAN version of **hyperSpec**.

**Comment by GegznaV** [comment]
Are all tasks in this issue completed?

**Comment by bryanhanson** [comment]
Yes, these are done, closing.  Some unit test issues to take care of but they are given in another issue.
